extends:
  - spectral:oas
  - governance-rules/governance-rules.yaml  # Include custom governance rules

rules:
  openapi-version:
    description: "OpenAPI specification must include a version."
    severity: error
    given: "$"
    then:
      field: "openapi"
      function: truthy

  info-description:
    description: "Info object should have a description."
    severity: warning
    given: "$.info"
    then:
      field: "description"
      function: truthy

  api-contact:
    description: "API specifications should include a contact field."
    severity: warning
    given: "$.info"
    then:
      field: "contact"
      function: truthy

  operation-summary:
    description: "Each API operation should have a summary."
    severity: warning
    given: "$.paths[*][*]"
    then:
      field: "summary"
      function: truthy

  operation-description:
    description: "Each API operation should have a description."
    severity: warning
    given: "$.paths[*][*]"
    then:
      field: "description"
      function: truthy

  operation-tags:
    description: "Each API operation should have at least one tag."
    severity: warning
    given: "$.paths[*][*]"
    then:
      field: "tags"
      function: truthy

  response-schema:
    description: "Responses should have a defined schema."
    severity: error
    given: "$.paths[*][*].responses[*]"
    then:
      field: "content.application/json.schema"
      function: truthy
